import Head from "next/head";

function About() {
  return (
    <>
      <Head>
        <title>About - CKI @ CPP</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/cki_logo.png" />
      </Head>
      <div>
        yes this is about me
      </div>
    </>
  );
}

export default About;